create_clock -name clk -period 20.000 [get_ports {clk}]
derive_pll_clocks
derive_clock_uncertainty

# External DE0-CV SDRAM interface.
# DRAM_CLK is generated by rtl/memory/sdram_clock_pll.vhd with a board-facing
# phase shift. These I/O delays are conservative 50 MHz constraints so Timing
# Analyzer no longer treats the SDRAM pins as unconstrained.
create_generated_clock -name sdram_clk_ext -source [get_ports {clk}] -divide_by 1 [get_ports {DRAM_CLK}]

set sdram_cmd_ports [get_ports {
    DRAM_ADDR[*]
    DRAM_BA[*]
    DRAM_CAS_N
    DRAM_CKE
    DRAM_CS_N
    DRAM_LDQM
    DRAM_RAS_N
    DRAM_UDQM
    DRAM_WE_N
}]
set sdram_dq_ports [get_ports {DRAM_DQ[*]}]

set_output_delay -clock sdram_clk_ext -max 3.000 $sdram_cmd_ports
set_output_delay -clock sdram_clk_ext -min -1.000 $sdram_cmd_ports

set_output_delay -clock sdram_clk_ext -max 3.000 $sdram_dq_ports
set_output_delay -clock sdram_clk_ext -min -1.000 $sdram_dq_ports
set_input_delay  -clock sdram_clk_ext -max 7.000 $sdram_dq_ports
set_input_delay  -clock sdram_clk_ext -min 1.000 $sdram_dq_ports
