param(
    [int]$N = 4,
    [int]$TileSize = 2,
    [int]$NumMacs = 2,
    [int]$DataWidth = 8,
    [int]$AccWidth = 32,

    [string]$MemType = "internal_fpga_ram",
    [string]$Dataflow = "output_stationary",
    [string]$BufferingMode = "single",
    [int]$MemoryBurstLen = 1,
    [int]$MacPipelineStages = 0,
    [int]$MemoryBanksA = 1,
    [int]$MemoryBanksB = 1,

    [int]$ClksPerBit = 434,
    [int]$ClkFreqHz = 50000000,
    [int]$UartFifoDepth = 64,
    [string]$EnableSignaltap = "false",

    [switch]$Clean,
    [switch]$UpdatePythonEnv,
    [switch]$Program
)

$ErrorActionPreference = "Stop"

$ProjectDir = $PSScriptRoot
$ProjectName = "fpga_matrix_accelerator"
$RevisionName = "fpga_matrix_accelerator"
$QsfPath = Join-Path $ProjectDir "$ProjectName.qsf"

Set-Location $ProjectDir

function Assert-PositiveInt {
    param(
        [string]$Name,
        [int]$Value
    )

    if ($Value -le 0) {
        throw "$Name precisa ser maior que zero. Valor recebido: $Value"
    }
}

function Test-AllowedValue {
    param(
        [string]$Name,
        [string]$Value,
        [string[]]$Allowed
    )

    if ($Allowed -notcontains $Value) {
        throw "$Name invalido: '$Value'. Valores aceitos: $($Allowed -join ', ')"
    }
}

function Find-QuartusTool {
    param([string]$Name)

    $cmd = Get-Command $Name -ErrorAction SilentlyContinue
    if ($null -ne $cmd) {
        return $cmd.Source
    }

    $fallback = "C:\altera_lite\25.1std\quartus\bin64\$Name.exe"
    if (Test-Path -LiteralPath $fallback) {
        return $fallback
    }

    throw "Ferramenta nao encontrada: $Name"
}

function Format-QsfValue {
    param([object]$Value)

    if ($Value -is [int]) {
        return "$Value"
    }

    $text = [string]$Value

    if ($text -match "^[0-9]+$") {
        return $text
    }

    if ($text -eq "true" -or $text -eq "false") {
        return $text
    }

    $escaped = $text.Replace("\", "\\").Replace('"', '\"')
    return '"' + $escaped + '"'
}

function Set-QsfGenericBlock {
    param(
        [string]$Path,
        [hashtable]$Generics
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Arquivo QSF nao encontrado: $Path"
    }

    $startMarker = "# >>> AUTO_GENERATED_GENERIC_PARAMETERS_START"
    $endMarker   = "# <<< AUTO_GENERATED_GENERIC_PARAMETERS_END"

    $original = Get-Content -LiteralPath $Path -Raw
    $original = $original.TrimStart([char]0xFEFF)

    $pattern = "(?s)`r?`n?$([regex]::Escape($startMarker)).*?$([regex]::Escape($endMarker))`r?`n?"
    $cleaned = [regex]::Replace($original, $pattern, "`r`n")

    $lines = @()
    $lines += ""
    $lines += $startMarker
    $lines += "# Generated by synth_fpga.ps1"
    $lines += "# These values override top-level VHDL generics for Quartus compilation."

    foreach ($key in $Generics.Keys | Sort-Object) {
        $value = Format-QsfValue $Generics[$key]
        $lines += "set_parameter -name $key $value"
    }

    $lines += $endMarker
    $lines += ""

    $newText = $cleaned.TrimEnd() + "`r`n" + ($lines -join "`r`n")
    $newText = $newText.TrimStart([char]0xFEFF)

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $newText, $utf8NoBom)
}

function Invoke-Step {
    param([string[]]$Command)

    Write-Host ""
    Write-Host ("$ " + ($Command -join " "))

    $exe = $Command[0]
    $args = @()
    if ($Command.Count -gt 1) {
        $args = $Command[1..($Command.Count - 1)]
    }

    & $exe @args

    if ($LASTEXITCODE -ne 0) {
        throw "Comando falhou com exit code ${LASTEXITCODE}: $($Command -join ' ')"
    }
}

function Remove-PathBestEffort {
    param(
        [string]$Path,
        [string]$Label,
        [int]$MaxAttempts = 5,
        [int]$RetrySeconds = 2
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    for ($attempt = 1; $attempt -le $MaxAttempts; $attempt++) {
        try {
            Write-Host "Removendo $Label..."
            Remove-Item -Recurse -Force -LiteralPath $Path -ErrorAction Stop
            return
        }
        catch {
            if ($attempt -lt $MaxAttempts) {
                Write-Warning "Nao consegui remover ${Label} na tentativa ${attempt}/${MaxAttempts}: $($_.Exception.Message)"
                Write-Warning "Aguardando $RetrySeconds segundo(s) e tentando de novo..."
                Start-Sleep -Seconds $RetrySeconds
            } else {
                Write-Warning "Nao consegui remover ${Label} apos ${MaxAttempts} tentativas: $($_.Exception.Message)"
                Write-Warning "Continuando compilacao sem limpeza completa de $Label. Feche Quartus/Questa se o erro persistir."
            }
        }
    }
}

function Update-PythonEnvFile {
    param([string]$EnvPath)

    $envDir = Split-Path -Parent $EnvPath
    if (-not (Test-Path -LiteralPath $envDir)) {
        New-Item -ItemType Directory -Force -Path $envDir | Out-Null
    }

    $content = @"
N=$N
NUM_TESTS=1
DATA_WIDTH=$DataWidth
ACC_WIDTH=$AccWidth
SEED=123
MIN_VALUE=-1
MAX_VALUE=1
EXAMPLE=false
MATRIX_OUTPUT_DIR=matrix
"@

    Set-Content -LiteralPath $EnvPath -Value $content -Encoding UTF8
    Write-Host "Atualizado .env do Python: $EnvPath"
}

Assert-PositiveInt -Name "N" -Value $N
Assert-PositiveInt -Name "TileSize" -Value $TileSize
Assert-PositiveInt -Name "NumMacs" -Value $NumMacs
Assert-PositiveInt -Name "DataWidth" -Value $DataWidth
Assert-PositiveInt -Name "AccWidth" -Value $AccWidth
Assert-PositiveInt -Name "MemoryBurstLen" -Value $MemoryBurstLen
Assert-PositiveInt -Name "MemoryBanksA" -Value $MemoryBanksA
Assert-PositiveInt -Name "MemoryBanksB" -Value $MemoryBanksB
Assert-PositiveInt -Name "ClksPerBit" -Value $ClksPerBit
Assert-PositiveInt -Name "ClkFreqHz" -Value $ClkFreqHz
Assert-PositiveInt -Name "UartFifoDepth" -Value $UartFifoDepth

if (($N % $TileSize) -ne 0) {
    throw "N precisa ser multiplo de TileSize. N=$N TileSize=$TileSize"
}

if ($MacPipelineStages -lt 0) {
    throw "MacPipelineStages precisa ser >= 0. Valor recebido: $MacPipelineStages"
}

Test-AllowedValue -Name "BufferingMode" -Value $BufferingMode -Allowed @("single", "double")
Test-AllowedValue -Name "EnableSignaltap" -Value $EnableSignaltap -Allowed @("true", "false")

$generics = @{
    "N"                   = $N
    "TILE_SIZE"           = $TileSize
    "NUM_MACS"            = $NumMacs
    "DATA_WIDTH"          = $DataWidth
    "ACC_WIDTH"           = $AccWidth
    "MEM_TYPE"            = $MemType
    "DATAFLOW"            = $Dataflow
    "BUFFERING_MODE"      = $BufferingMode
    "MEMORY_BURST_LEN"    = $MemoryBurstLen
    "MAC_PIPELINE_STAGES" = $MacPipelineStages
    "MEMORY_BANKS_A"      = $MemoryBanksA
    "MEMORY_BANKS_B"      = $MemoryBanksB
    "CLKS_PER_BIT"        = $ClksPerBit
    "CLK_FREQ_HZ"         = $ClkFreqHz
    "UART_FIFO_DEPTH"     = $UartFifoDepth
    "ENABLE_SIGNALTAP"    = $EnableSignaltap
}

Write-Host "Configurando generics no QSF:"
$generics.GetEnumerator() | Sort-Object Name | ForEach-Object {
    Write-Host ("  {0} = {1}" -f $_.Key, $_.Value)
}

Set-QsfGenericBlock -Path $QsfPath -Generics $generics

if ($UpdatePythonEnv) {
    $envPath = Join-Path $ProjectDir "py_matrix_host\.env"
    Update-PythonEnvFile -EnvPath $envPath
}

if ($Clean) {
    foreach ($dir in @("db", "incremental_db", "output_files")) {
        $path = Join-Path $ProjectDir $dir
        Remove-PathBestEffort -Path $path -Label $dir
    }
}

$quartusSh = Find-QuartusTool "quartus_sh"

Invoke-Step -Command @(
    $quartusSh,
    "--flow",
    "compile",
    $ProjectName,
    "-c",
    $RevisionName
)

$sofPath = Join-Path $ProjectDir "output_files\$ProjectName.sof"

if (Test-Path -LiteralPath $sofPath) {
    Write-Host ""
    Write-Host "SOF gerado:"
    Write-Host "  $sofPath"
} else {
    Write-Warning "Compile terminou, mas nao achei o SOF esperado em: $sofPath"
}

if ($Program) {
    if (-not (Test-Path -LiteralPath $sofPath)) {
        throw "Nao posso programar a FPGA: SOF nao encontrado em $sofPath"
    }

    $quartusPgm = Find-QuartusTool "quartus_pgm"

    Invoke-Step -Command @(
        $quartusPgm,
        "-m",
        "JTAG",
        "-o",
        "p;$sofPath"
    )
}
